### ISSUE TITLE
We need releases for arm32 architectures! ✊

### ISSUE THREAD

**Issue by masterjavaofficial** [Lzhiyong/sdk-tools#11]
Please!!!

**Comment by Lzhiyong** [comment]
Please try compiling it for armv7a by yourself.
if you encounter errors, refer to the corresponding Android.bp file.

**Comment by masterjavaofficial** [comment]
> Please try compiling it for armv7a by yourself. if you encounter errors, refer to the corresponding Android.bp file.

I don't have a PC (so I can't use Android NDK😒) to build it for my armv7a architecture device. And the NDK you provide for phones are only for aarch64, that's also unsupported by my arch.😒

**Comment by Lzhiyong** [comment]
> > Please try compiling it for armv7a by yourself. if you encounter errors, refer to the corresponding Android.bp file.
> 
> I don't have a PC (so I can't use Android NDK😒) to build it for my armv7a architecture device. And the NDK you provide for phones are only for aarch64, that's also unsupported by my arch.😒

I guess you may need aapt2 to compile the Android App.

**Comment by masterjavaofficial** [comment]
> > > Please try compiling it for armv7a by yourself. if you encounter errors, refer to the corresponding Android.bp file.
> > 
> > 
> > I don't have a PC (so I can't use Android NDK😒) to build it for my armv7a architecture device. And the NDK you provide for phones are only for aarch64, that's also unsupported by my arch.😒
> 
> I guess you may need aapt2 to compile the Android App.


Yes, I don't need the NDK, I only need the build tools (like aapt, aapt2 etc..). But building these tools for my arch from a PC doesn't need the NDK? I told about that. I don'

**Comment by Lzhiyong** [comment]
I have compiled it for arm architecture, but I haven’t tested it, because I don’t have an armv7a device, you can try it, download from release.

**Comment by masterjavaofficial** [comment]
> I have compiled it for arm architecture, but I haven’t tested it, because I don’t have an armv7a device, you can try it, download from release.

Btw when did you add arm32 releases??! I didn't see it before so I opened this issue 🥴

**Comment by Lzhiyong** [comment]
> > I have compiled it for arm architecture, but I haven’t tested it, because I don’t have an armv7a device, you can try it, download from release.
> 
> Btw when did you add arm32 releases??! I didn't see it before so I opened this issue 🥴

(sdk-tools-static-arm.zip)[https://github.com/Lzhiyong/sdk-tools/releases]
