### ISSUE TITLE
Need Support For sdk32 build tools 

### ISSUE THREAD

**Issue by freindlytech** [Lzhiyong/sdk-tools#12]
Just to be updated with google and want to use latest tools so Sir can you plz provide all build tools for aapt2

**Comment by Lzhiyong** [comment]
> Just to be updated with google and want to use latest tools so Sir can you plz provide all build tools for aapt2

Usually I will update it once every few months. If you need the latest version of aapt2, you may need to compile it yourself. You can refer to this tutorial of mine or others.

**Comment by freindlytech** [comment]
> > Just to be updated with google and want to use latest tools so Sir can you plz provide all build tools for aapt2
> 
> Usually I will update it once every few months. If you need the latest version of aapt2, you may need to compile it yourself. You can refer to this tutorial of mine or others.

It means we will get aapt2 of sdk32 next month ??

**Comment by Lzhiyong** [comment]
> It means we will get aapt2 of sdk32 next month ??
The termux already supports build-tools, and I will update it from time to time.

**Comment by freindlytech** [comment]
> > It means we will get aapt2 of sdk32 next month ??
> 
> The termux already supports build-tools, and I will update it from time to time.

But aapt2 of termux didn't work with agp(7.3.0-alpha01) and it needs to be updated

**Comment by Lzhiyong** [comment]
> But aapt2 of termux didn't work with agp(7.3.0-alpha01) and it needs to be updated

Please wait for the official termux to fix it.

**Comment by freindlytech** [comment]
Ya I am regularly reporting aapt2 error to termux developer of every release cauz I am the one who request and get aapt2 and will.

**Comment by freindlytech** [comment]
@Lzhiyong  
Successfully Run gradle(agp 7.3.1-alpha01)with aapt2 made by @xtkoba, I am now happy to get sdk32 support 😊

Here is the Screenshot link 
https://github.com/termux/termux-packages/issues/8887#issuecomment-1033814515
