### ISSUE TITLE
libziparchive @ 2c01112 points to an "empty" dir

### ISSUE THREAD

**Issue by neugartf** [Lzhiyong/sdk-tools#13]
Looks like the submodule libziparchive is pointing to https://cs.android.com/android/_/android/platform/system/libziparchive/+/2c011122, which just contains a config. 
I assume the "correct" one is https://cs.android.com/android/_/android/platform/system/libziparchive/+/38bcc139f44eb4d9ccfb612c26d91a3ddefc3b00?

**Comment by Lzhiyong** [comment]
libziparchive doesn't have a master branch, so one needs to be set up manually.
```bash
# branch android12-mainline-release or others
git config -f .gitmodules submodule.src/libziparchive.branch android12-mainline-release

git submodule sync

git submodule update --depth=1 --init --recursive

git submodule update --remote
```

**Comment by Lzhiyong** [comment]
Now use `get_source.py` to download the source code
