### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RohitVermaOP** [Lzhiyong/sdk-tools#16]
When i compile Android-12 aapt source code then it can run on android version 5,6,7,8,... devices or not??

**Comment by Lzhiyong** [comment]
> When i compile Android-12 aapt source code then it can run on android version 5,6,7,8,... devices or not??

You can download the compiled binaries for testing, they are all statically linked and should work fine.

**Comment by RohitVermaOP** [comment]
> 

Ok, thanks

**Comment by RohitVermaOP** [comment]
![Screenshot_2022-03-10-15-07-26-36_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/56387351/157634645-8e671f7f-3512-49b0-9de2-99db930bb752.jpg)
Why generated lib size is too high

**Comment by Lzhiyong** [comment]
> Why generated lib size is too high

llvm-strip -g *.a 
strip -g *.a

**Comment by RohitVermaOP** [comment]
> > Why generated lib size is too high
> 
> llvm-strip -g *.a strip -g *.a

Put this code on CMakeLists.txt ??

**Comment by RohitVermaOP** [comment]
> > Why generated lib size is too high
> 
> llvm-strip -g *.a strip -g *.a

Thanks

**Comment by RohitVermaOP** [comment]
![Uploading Screenshot_2022-03-10-21-07-10-54_84d3000e3f4017145260f7618db1d683.jpg…]()
Error when compling aidl

**Comment by Lzhiyong** [comment]
> Error when compling aidl

redownload `sdk-tools-source.zip` and compile with `ndk-r23b`

```bash
NDK_TOOLCHAIN=/path/to/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64

cmake -G 'Ninja' \
    -DCMAKE_C_COMPILER=$NDK_TOOLCHAIN/bin/aarch64-linux-android30-clang \
    -DCMAKE_CXX_COMPILER=$NDK_TOOLCHAIN/bin/aarch64-linux-android30-clang++ \
    -DCMAKE_SYSROOT=$NDK_TOOLCHAIN/sysroot \
    -DCMAKE_BUILD_TYPE=Release \
    ..

# patch aidl_language_y.h
ninja patch

ninja -j16
```

**Comment by RohitVermaOP** [comment]
It doesn't working,
Others way to patch aidl_language_y.h ???

**Comment by Lzhiyong** [comment]
> It doesn't working, Others way to patch aidl_language_y.h ???

modify the `aidl_language_y.h`
```h
// add these two lines at the end of the file
typedef union yy::parser::value_type YYSTYPE;
typedef yy::parser::location_type YYLTYPE;
```

**Comment by RohitVermaOP** [comment]
> > It doesn't working, Others way to patch aidl_language_y.h ???
> 
> modify the `aidl_language_y.h`
> 
> ```c
> // add these two lines at the end of the file
> typedef union yy::parser::value_type YYSTYPE;
> typedef yy::parser::location_type YYLTYPE;
> ```

Same happened

**Comment by RohitVermaOP** [comment]
![Screenshot_2022-03-18-15-09-07-55_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/56387351/158979109-5e82dc84-44c6-4084-a7bc-70efb0aa28a8.jpg)
When i compile whole source

**Comment by RohitVermaOP** [comment]
aapt, aapt2 link error
![Screenshot_2022-04-27-21-55-41-53_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/56387351/165578113-557cf5c2-06e7-4036-8d5c-bdbd6c136ecb.jpg)

**Comment by RohitVermaOP** [comment]
Getting error while compiling for x86 and x86_64

**Comment by Lzhiyong** [comment]
> Getting error while compiling for x86 and x86_64

modify the `src/boringssl/CMakeLists.txt`, start at line 500
```CMakeLists.txt
# set ARCH and MARCH
set(MARCH)
if(ANDROID_ABI MATCHES "arm64-v8a")
    set(ARCH "aarch64")
    set(MARCH "aarch64")
elseif(ANDROID_ABI MATCHES "armeabi-v7a")
    set(ARCH "arm")
    set(MARCH ${ANDROID_ABI})
elseif(ANDROID_ABI MATCHES "x86")
    set(ARCH "x86")
    set(MARCH "i386")
else(ANDROID_ABI MATCHES "x86_64")
    set(ARCH "x86_64")
    set(MARCH ${ANDROID_ABI})
endif()

# set -march flag == ${MARCH}
if(ANDROID AND NOT ANDROID_NDK_REVISION AND ARCH STREQUAL "arm")
  # The third-party Android-NDK CMake files somehow fail to set the -march flag
  # for assembly files. Without this flag, the compiler believes that it's
  # building for ARMv5.
  set(CMAKE_ASM_FLAGS "-march=${MARCH} ${CMAKE_ASM_FLAGS}")
endif()
```
build.sh
```bash
# ANDROID_ABI = arm64-v8a, armeabi-v7a, x86, x86_64

cmake -G 'Ninja' \
    -DCMAKE_C_COMPILER=$NDK_TOOLCHAIN/bin/aarch64-linux-android30-clang \
    -DCMAKE_CXX_COMPILER=$NDK_TOOLCHAIN/bin/aarch64-linux-android30-clang++ \
    -DCMAKE_SYSROOT=$NDK_TOOLCHAIN/sysroot \
    -DCMAKE_BUILD_TYPE=Release \
    -DANDROID_ABI=x86
    ..
```

**Comment by Lzhiyong** [comment]
![IMG_20220428_140141](https://user-images.githubusercontent.com/36750502/165687652-80415539-6b7e-4221-87ae-a48257acfe09.jpg)
I just tested aapt2 briefly, there may be other errors, please refer to the corresponding Android.bp and CMakeLists.txt to modify

**Comment by RohitVermaOP** [comment]
![Screenshot_2022-04-28-13-00-59-60_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/56387351/165707704-693a1514-ac54-4db7-b16c-0484c7b73ec4.jpg)
```clang-12: error: the clang compiler does not support '-march=i686'```

**Comment by Lzhiyong** [comment]
> `clang-12: error: the clang compiler does not support '-march=i686'`

Sorry, there is an error in the above command, it should be for x86
```bash
-DCMAKE_C_COMPILER=$NDK_TOOLCHAIN/bin/i686-linux-android30-clang \
-DCMAKE_CXX_COMPILER=$NDK_TOOLCHAIN/bin/i686-linux-android30-clang++ \
```

**Comment by RohitVermaOP** [comment]
Thanks, it worked.

**Comment by RohitVermaOP** [comment]
![Screenshot_2022-04-28-23-28-38-39_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/56387351/165817365-42cd30ef-b6df-4ba4-a6ee-0c30bdbc158a.jpg)
adb linking error

**Comment by RohitVermaOP** [comment]
> ![Screenshot_2022-04-28-23-28-38-39_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/56387351/165817365-42cd30ef-b6df-4ba4-a6ee-0c30bdbc158a.jpg) adb linking error

This is last error!

**Comment by Lzhiyong** [comment]
not generating cpp files correctly, for cross compiling you need host `protoc`

put the aarch64 protoc executable in your `x86 build/bin` directory

no need to execute the `ninja protoc` command for cross compilation
