### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by yutong-yt** [Lzhiyong/sdk-tools#18]
![Screenshot_2022-04-27-09-05-42-411_com termux](https://user-images.githubusercontent.com/84581911/165417915-05df84c8-3b09-4943-b965-0878f0afbc60.jpg)
什么原因？

**Comment by Lzhiyong** [comment]
应该直接在Termux里进行构建，不需要使用proot-distro

**Comment by yutong-yt** [comment]
可是我想编译linux版本的啊


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 上午10:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
应该直接在Termux里进行构建，不需要使用proot-distro
 
&mdash;

**Comment by Lzhiyong** [comment]
静态链接的在linux下一样可以执行，如果要编译linux版本，你需要自重新下载源码，然后打补丁

openjdk-17官方已经为android12打补丁了，所以大多数情况下是不需要使用proot

另外linux版本是不能使用ndk进行编译的，应该使用linux下的clang或gcc进行编译

**Comment by yutong-yt** [comment]
补丁如何打


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午11:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
静态链接的在linux下一样可以执行，如果要编译linux版本，你需要自重新下载源码，然后打补丁
 
openjdk-17官方已经为android12打补丁了，所以大多数情况下是不需要使用proot
 
另外linux版本是不能使用ndk进行编译的，应该使用linux下的clang或gcc进行编译
 
&mdash;

**Comment by Lzhiyong** [comment]
克隆sdk-tools仓库

使用get_source.py下载源码

参照patches/*.patch进行手工更改，因为源码来源于master分支，谷歌更新的速度非常快，所以不能在脚本里进行自动打补丁

patches/cmake下的文件不需要改动，这些是针对ndk做的改动

patches/other也不需要手工操作，get_source.py会自动把这些文件复制到相应的目录

**Comment by yutong-yt** [comment]
我只想编译linux&nbsp;arm64版本的aapt2


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午11:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
克隆sdk-tools仓库
 
使用get_source.py下载源码
 
参照patches/*.patch进行手工更改，因为源码来源于master分支，谷歌更新的速度非常快，所以不能在脚本里进行自动打补丁
 
patches/cmake下的文件不需要改动，这些是针对ndk做的改动
 
patches/other也不需要手工操作，get_source.py会自动把这些文件复制到相应的目录
 
&mdash;

**Comment by yutong-yt** [comment]
我已经下载了下载源码


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午11:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
克隆sdk-tools仓库
 
使用get_source.py下载源码
 
参照patches/*.patch进行手工更改，因为源码来源于master分支，谷歌更新的速度非常快，所以不能在脚本里进行自动打补丁
 
patches/cmake下的文件不需要改动，这些是针对ndk做的改动
 
patches/other也不需要手工操作，get_source.py会自动把这些文件复制到相应的目录
 
&mdash;

**Comment by yutong-yt** [comment]
我不知道编译命令是什么？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午11:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
克隆sdk-tools仓库
 
使用get_source.py下载源码
 
参照patches/*.patch进行手工更改，因为源码来源于master分支，谷歌更新的速度非常快，所以不能在脚本里进行自动打补丁
 
patches/cmake下的文件不需要改动，这些是针对ndk做的改动
 
patches/other也不需要手工操作，get_source.py会自动把这些文件复制到相应的目录
 
&mdash;

**Comment by yutong-yt** [comment]
可否加个QQ好友？这上面交流太不方便了。QQ：2422730738

**Comment by Lzhiyong** [comment]
只编译aapt2，可以把其它不需要的都注释掉，当然lib下的不能注释

你可能会遇到一些新的错误，当然这些需要你自己去解决了

```bash
mkdir build && cd build

# gcc or clang
cmake -G 'Ninja' \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    ..
```

**Comment by yutong-yt** [comment]
这是成功了还是失败了？下一步是什么？

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午11:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
只编译aapt2，可以把其它不需要的都注释掉，当然lib下的不能注释
 
你可能会遇到一些新的错误，当然这些需要你自己去解决了
 mkdir build &amp;&amp; cd build # gcc or clang cmake -G 'Ninja' \     -DCMAKE_C_COMPILER=clang \     -DCMAKE_CXX_COMPILER=clang++ \     ..

**Comment by yutong-yt** [comment]
这是成功了吗？下一步是什么？
![Screenshot_2022-04-27-11-41-01-954_com termux](https://user-images.githubusercontent.com/84581911/165435577-a268b38a-ec67-4b07-b48e-300cd6408ddd.jpg)
![Screenshot_2022-04-27-11-40-58-045_com termux](https://user-images.githubusercontent.com/84581911/165435578-b2717398-31d8-4d68-b682-939962809df6.jpg)
![Screenshot_2022-04-27-11-41-11-048_com termux](https://user-images.githubusercontent.com/84581911/165435558-ee1d930c-0c39-4c4d-a81e-fb301e8954f9.jpg)
![Screenshot_2022-04-27-11-41-08-894_com termux](https://user-images.githubusercontent.com/84581911/165435567-ab785209-8256-47a3-a0ee-230d8a8db650.jpg)
![Screenshot_2022-04-27-11-41-05-699_com termux](https://user-images.githubusercontent.com/84581911/165435571-09f433ec-2d6e-4cec-885b-f48c65c91c74.jpg)
![Screenshot_2022-04-27-11-41-03-904_com termux](https://user-images.githubusercontent.com/84581911/165435573-88f9ce7d-c33f-45b4-a0ad-cfed469658f1.jpg)

**Comment by Lzhiyong** [comment]
ninja aprotoc

# 在执行一次build.sh
bash build.sh

ninja aapt2

**Comment by yutong-yt** [comment]
失败了
![Screenshot_2022-04-27-12-01-18-796_com termux](https://user-images.githubusercontent.com/84581911/165437901-0cf29013-4a9c-4868-86b5-fd8421fef180.jpg)

**Comment by Lzhiyong** [comment]
参照[patches/cmake/abseil_CMakeLists.txt.patch](https://github.com/Lzhiyong/sdk-tools/blob/master/patches/cmake/abseil_CMakeLists.txt.patch) 进行修改

**Comment by yutong-yt** [comment]
修改哪个文件？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午12:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
参照patches/cmake/abseil_CMakeLists.txt.patch 进行修改
 
&mdash;

**Comment by Lzhiyong** [comment]
src/abseil-cpp/CMakeLists.txt

**Comment by yutong-yt** [comment]
直接把https://github.com/Lzhiyong/sdk-tools/blob/master/patches/cmake/abseil_CMakeLists.txt.patch复制过去可以吗？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午12:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
src/abseil-cpp/CMakeLists.txt
 
&mdash;

**Comment by yutong-yt** [comment]
完全不知道如何修改
![
![IMG_20220427_121131](https://user-images.githubusercontent.com/84581911/165439034-063cfbd1-6fdc-4685-ba2c-fde64f0b3746.jpg)
Uploading Screenshot_2022-04-27-12-11-44-063_com.yt.wjzg.jpg…]()

**Comment by yutong-yt** [comment]
![Screenshot_2022-04-27-12-11-44-063_com yt wjzg](https://user-images.githubusercontent.com/84581911/165439207-570b4260-3557-4cdb-990e-0d6efb93f8ad.jpg)
![IMG_20220427_121131](https://user-images.githubusercontent.com/84581911/165439220-9f7eaf2f-ed42-43fa-9709-d614341b775a.jpg)

**Comment by yutong-yt** [comment]
看懂了

**Comment by Lzhiyong** [comment]
你看上面那个补丁文件，第7 8行 以及第17 18行
改成+号所在的哪一行 就是背景是绿色的那一行就行. 😓😓

**Comment by yutong-yt** [comment]
修改了，还是报错
![Screenshot_2022-04-27-12-35-46-412_bin mt plus](https://user-images.githubusercontent.com/84581911/165441824-8ae3c296-6148-4fa2-ba5c-627de2cba651.jpg)
![Screenshot_2022-04-27-12-37-38-297_com termux](https://user-images.githubusercontent.com/84581911/165441828-4e32fcc4-1465-45c3-96f9-7587601f55ae.jpg)
[CMakeLists.txt](https://github.com/Lzhiyong/sdk-tools/files/8568873/CMakeLists.txt)

**Comment by Lzhiyong** [comment]
删除缓存文件build/CMakeCache.txt，重新执行build.sh

**Comment by Lzhiyong** [comment]
我觉得你应该适当的学习一下cmake，这样改起来会轻松很多，现在android也是以cmake为主了

**Comment by yutong-yt** [comment]
哦


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午1:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
我觉得你应该适当的学习一下cmake，这样改起来会轻松很多，现在android也是以cmake为主了
 
&mdash;

**Comment by yutong-yt** [comment]
还是报错
 ![Screenshot_2022-04-27-13-11-50-569_com termux](https://user-images.githubusercontent.com/84581911/165445214-3c5be258-f1b8-4dda-bb3c-e2cb36556efe.jpg)

**Comment by Lzhiyong** [comment]
ls看下这个目录/home/sdk-tools/src/protobuf/third_party/googletest存不存在！

**Comment by yutong-yt** [comment]
有这个目录，但是里面没有任何东西
![Screenshot_2022-04-27-13-17-21-094_com termux](https://user-images.githubusercontent.com/84581911/165445719-29448249-f788-4b65-9af9-5a7dc088e0e4.jpg)

**Comment by Lzhiyong** [comment]
你的源码没有克隆下来

**Comment by yutong-yt** [comment]
哦，需要重新克隆吗？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午1:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
你的源码没有克隆下来
 
&mdash;

**Comment by Lzhiyong** [comment]
切换到sdk-tools
删除src/protobuf

单独克隆protobuf
git submodule update --depth=1 --init src/protobuf

git submodule update --remote src/protobuf

**Comment by yutong-yt** [comment]
好的


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午1:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
切换到sdk-tools
 删除src/protobuf
 
单独克隆protobuf
 git submodule update --depth=1 --init src/protobuf
 
git submodule update --remote src/protobuf
 
&mdash;

**Comment by yutong-yt** [comment]
我可不可以选择不打包他？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午1:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
切换到sdk-tools
 删除src/protobuf
 
单独克隆protobuf
 git submodule update --depth=1 --init src/protobuf
 
git submodule update --remote src/protobuf
 
&mdash;

**Comment by yutong-yt** [comment]
毕竟我想要的只有aapt2，aapt而以


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午1:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
切换到sdk-tools
 删除src/protobuf
 
单独克隆protobuf
 git submodule update --depth=1 --init src/protobuf
 
git submodule update --remote src/protobuf
 
&mdash;

**Comment by Lzhiyong** [comment]
是否编译成功了？
不会自动打包的，打包需要执行ninja package

编译成功后，生成的可执行文件在build/bin

**Comment by yutong-yt** [comment]
没有，运行ninja&nbsp;package&nbsp;&nbsp;提示
ninja:&nbsp;error:&nbsp;loading&nbsp;'build.ninja':&nbsp;No&nbsp;such&nbsp;file&nbsp;or&nbsp;directory


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午1:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
是否编译成功了？
 不会自动打包的，打包需要执行ninja package
 
编译成功后，生成的可执行文件在build/bin
 
&mdash;

**Comment by yutong-yt** [comment]
我在等别人帮我下载文件，我没有办法访问外网


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午1:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
是否编译成功了？
 不会自动打包的，打包需要执行ninja package
 
编译成功后，生成的可执行文件在build/bin
 
&mdash;

**Comment by Lzhiyong** [comment]
你的源码还没下载下来？
可以直接下载release/sdk-tools-source.zip
然后复制protobuf到你的目录就可以(只需复制protobuf，因为我的这个源码是打过补丁的，你在linux下编译可能会有问题的！)

**Comment by yutong-yt** [comment]
我是安装git&nbsp;clone&nbsp;--depth=1&nbsp;https://github.com/Lzhiyong/sdk-tools
cd&nbsp;sdk-tools
python&nbsp;get_source.py
进行下载的


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 下午2:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
你的源码还没下载下来？
 可以直接下载release/sdk-tools-source.zip
 然后复制protobuf到你的目录就可以(只需复制protobuf，因为我的这个源码是打过补丁的，你在linux下编译可能会有问题的！)
 
&mdash;

**Comment by yutong-yt** [comment]
出现了新的错误
![Screenshot_2022-04-27-14-25-01-739_com termux](https://user-images.githubusercontent.com/84581911/165454725-a7169457-5887-49c5-a760-87f9f833ccc3.jpg)
![Screenshot_2022-04-27-14-25-05-150_com termux](https://user-images.githubusercontent.com/84581911/165454735-d9522ae0-ffac-476f-ac16-d8a639c94803.jpg)

**Comment by Lzhiyong** [comment]
参考[patches/cmake/protobuf_CMakeLists.txt.patch](https://github.com/Lzhiyong/sdk-tools/blob/master/patches/cmake/protobuf_CMakeLists.txt.patch)
修改src/protobuf/cmake/CMakeLists txt

参考patches/proto下的补丁
修改src/base/tools/aapt2/Resources.proto
修改src/base/tools/aapt2/ResourcesInternal.proto

**Comment by yutong-yt** [comment]
好的


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 下午2:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
参考patches/cmake/protobuf_CMakeLists.txt.patch
 修改src/protobuf/cmake/CMakeLists txt
 
参考patches/proto下的补丁
 修改src/base/tools/aapt2/Resources.proto
 修改src/base/tools/aapt2/ResourcesInternal.proto
 
&mdash;

**Comment by yutong-yt** [comment]
这算是成功了？
![Screenshot_2022-04-27-15-14-56-911_com termux](https://user-images.githubusercontent.com/84581911/165462508-098a31f7-2c20-49d7-b295-c4adcd12f17c.jpg)

**Comment by yutong-yt** [comment]
又有新的错误
![Uploading Screenshot_2022-04-27-15-18-25-385_com.termux.jpg…]()

**Comment by yutong-yt** [comment]
新的错误
![Screenshot_2022-04-27-15-18-19-944_com termux](https://user-images.githubusercontent.com/84581911/165463765-f9d63919-f55c-4802-9ab0-ab0889f5a280.jpg)
![Screenshot_2022-04-27-15-18-16-723_com termux](https://user-images.githubusercontent.com/84581911/165463872-df49c7e3-c0d2-49f3-87f5-859f2aed2b36.jpg)
![Screenshot_2022-04-27-15-18-14-057_com termux](https://user-images.githubusercontent.com/84581911/165463880-15c81bde-3fa0-4a52-a4b7-5f9b3bd7c7c0.jpg)
![Screenshot_2022-04-27-15-18-10-512_com termux](https://user-images.githubusercontent.com/84581911/165463888-69763ec0-038a-48bd-8c10-2f9151dd7ead.jpg)
![Screenshot_2022-04-27-15-18-07-007_com termux](https://user-images.githubusercontent.com/84581911/165463893-2a5f97f9-8f18-46c2-81a4-f53b77013cfb.jpg)
![Screenshot_2022-04-27-15-18-02-481_com termux](https://user-images.githubusercontent.com/84581911/165463897-ddd4b00d-ca61-4903-84ea-c0261487a583.jpg)
![Screenshot_2022-04-27-15-17-57-907_com termux](https://user-images.githubusercontent.com/84581911/165463900-caab55b1-7854-46a5-a9d7-6269d0510b3d.jpg)

**Comment by Lzhiyong** [comment]
都是警告，没看到具体的错误！

**Comment by yutong-yt** [comment]
![Screenshot_2022-04-27-15-27-53-975_com termux](https://user-images.githubusercontent.com/84581911/165464803-8ed6d511-fdd0-443b-adfc-4dc5937fe574.jpg)

**Comment by Lzhiyong** [comment]
没有libz.a
关闭静态编译把sdk-tools/CMakeLists.txt  26行注释掉

**Comment by yutong-yt** [comment]
成功了，哪下一步是啥？我想了想还是全部打包吧。命令是啥？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 下午3:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
没有libz.a
 关闭静态编译把sdk-tools/CMakeLists.txt  26行注释掉
 
&mdash;

**Comment by Lzhiyong** [comment]
你应该先成功编译aapt2，再去编译其它的，还有一些文件你需要修改

build.sh 

ninja aapt2

**Comment by yutong-yt** [comment]
出现了新的错误
![Screenshot_2022-04-27-15-47-13-478_com termux](https://user-images.githubusercontent.com/84581911/165468315-3bc7b78c-e0ca-4c4f-b462-994e399c4a8c.jpg)

**Comment by Lzhiyong** [comment]
err_data.c这个文件的生成，对网络是有要求的，你可能需要科学上网

**Comment by Lzhiyong** [comment]
[err_data.txt](https://github.com/Lzhiyong/sdk-tools/files/8570132/err_data.txt)
把文件重命名err_data.c，放到build/src/boringssl/crypto/

**Comment by yutong-yt** [comment]
没有用，一运行ninja&nbsp;aapt2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;哪个文件就又变成0mb了


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 下午4:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
err_data.txt
 把文件重命名err_data.c，放到build/src/boringssl/crypto/
 
&mdash;

**Comment by yutong-yt** [comment]
这是成功了吗？我修改了go的源
![Screenshot_2022-04-27-16-34-30-905_com termux](https://user-images.githubusercontent.com/84581911/165477160-610682dc-ca70-4d33-a568-61e40193c8be.jpg)

**Comment by yutong-yt** [comment]
哦豁失败了

**Comment by yutong-yt** [comment]
失败了

**Comment by yutong-yt** [comment]
出现了新的错误
![Screenshot_2022-04-27-16-39-50-679_com termux](https://user-images.githubusercontent.com/84581911/165478215-1ddafd2e-e67f-4bde-8736-f4bde43acb1d.jpg)
![Screenshot_2022-04-27-16-39-44-416_com termux](https://user-images.githubusercontent.com/84581911/165478226-9303e0a8-b538-4054-b02e-38ae2a304a32.jpg)
![Screenshot_2022-04-27-16-39-34-700_com termux](https://user-images.githubusercontent.com/84581911/165478231-54f0102b-1e0e-43a3-a340-beb4cd2b3a75.jpg)

**Comment by yutong-yt** [comment]
如何解决

**Comment by yutong-yt** [comment]
这种情况是不是需要修改C语言

**Comment by Lzhiyong** [comment]
这个有点麻烦，你需要有一份linux-aarch64交叉编译器的sysroot，这里面有些函数并不是glibc里面的，谷歌编译aosp本身也是用的交叉编译器，而不是用原生的linux和glibc

**Comment by yutong-yt** [comment]
有sysroot


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
这个有点麻烦，你需要有一份linux-aarch64交叉编译器的sysroot，这里面有些函数并不是glibc里面的，谷歌编译aosp本身也是用的交叉编译器，而不是用原生的linux和glibc
 
&mdash;

**Comment by Lzhiyong** [comment]
如果你非要在linux下成功编译，那这里面有很多的源码要进行修改，我不太建议你这么干
termux的proot对安卓做了很大的改动，可以直接运行安卓里面的可执行文件，所以不一定非要编译成linux下的
使用proot大多无非两种情况，GUI以及安卓tagged pointer问题 不能用openjdk，关于tagged pointer，termux已经有解决方法了，可以查看termux-packages的PR

**Comment by yutong-yt** [comment]
链接可不可以发一下？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 晚上7:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
如果你非要在linux下成功编译，那这里面有很多的源码要进行修改，我不太建议你这么干
 termux的proot对安卓做了很大的改动，可以直接运行安卓里面的可执行文件，所以不一定非要编译成linux下的
 使用proot大多无非两种情况，GUI以及安卓tagged pointer问题 不能用openjdk，关于tagged pointer，termux已经有解决方法了，可以查看termux-packages的PR
 
&mdash;

**Comment by yutong-yt** [comment]
其实我正在使用proot的原因是termux不支持Android5-6，老版本又不支持gradle与jdk。其次是Android12所以目前我知道的方法是使用32位的，但是不想使用32位的。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 晚上7:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
如果你非要在linux下成功编译，那这里面有很多的源码要进行修改，我不太建议你这么干
 termux的proot对安卓做了很大的改动，可以直接运行安卓里面的可执行文件，所以不一定非要编译成linux下的
 使用proot大多无非两种情况，GUI以及安卓tagged pointer问题 不能用openjdk，关于tagged pointer，termux已经有解决方法了，可以查看termux-packages的PR
 
&mdash;

**Comment by yutong-yt** [comment]
这个错误怎么解决？
![Screenshot_2022-04-28-09-05-01-062_com termux](https://user-images.githubusercontent.com/84581911/165655885-536a95f4-81de-40cd-894e-ac6c4b725a6b.jpg)

**Comment by yutong-yt** [comment]
![Screenshot_2022-04-28-09-05-01-062_com termux](https://user-images.githubusercontent.com/84581911/165655950-e8c8d348-eaec-46b9-895b-5db8ce1d6869.jpg)

**Comment by Lzhiyong** [comment]
patches/cmake/pcre_CMakeLists.txt.patch这个补丁是不需要打的，src/pcre/CMakeLists.txt保持原来的就可以了

不建议你编译，即使cmake配置成功了，后续还有很多链接的错误，如果你不能自己修复这些问题，还是直接使用编译好的二进制，一样可以在linux下执行，我是不可能帮助你解决所有的问题，Debug的能力也是你成为一名优秀工程师的基本条件

可以使用一些打印函数输出一些变量，然后退出程序，看看是否符合你的预期值等等！

**Comment by yutong-yt** [comment]
哦


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月28日(周四) 下午2:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
patches/cmake/pcre_CMakeLists.txt.patch这个补丁是不需要打的，src/pcre/CMakeLists.txt保持原来的就可以了
 
不建议你编译，即使cmake配置成功了，后续还有很多链接的错误，如果你不能自己修复这些问题，还是直接使用编译好的二进制，一样可以在linux下执行，我是不可能帮助你解决所有的问题，Debug的能力也是你成为一名优秀工程师的基本条件
 
可以使用一些打印函数输出一些变量，然后退出程序，看看是否符合你的预期值等等！
 
&mdash;

**Comment by yutong-yt** [comment]
哦


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 下午3:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
err_data.c这个文件的生成，对网络是有要求的，你可能需要科学上网
 
&mdash;

**Comment by yutong-yt** [comment]
好的


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 下午4:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
err_data.txt
 把文件重命名err_data.c，放到build/src/boringssl/crypto/
 
&mdash;

**Comment by yutong-yt** [comment]
如果不打包他，应该修改哪个文件？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 中午1:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/sdk-tools] 无法编译 (Issue #18)




 
切换到sdk-tools
 删除src/protobuf
 
单独克隆protobuf
 git submodule update --depth=1 --init src/protobuf
 
git submodule update --remote src/protobuf
 
&mdash;
