### ISSUE TITLE
aidl相关问题。

### ISSUE THREAD

**Issue by yutong-yt** [Lzhiyong/sdk-tools#20]
打包FBlackBox/BlackBox项目的时候因为所以到了aidl而报错，有什么解决方法吗？

![Screenshot_2022-05-09-20-28-40-515_com termux](https://user-images.githubusercontent.com/84581911/167410208-a14aa10c-c5ed-4362-94ef-47b1d6bf7d29.jpg)
![Screenshot_2022-05-09-20-28-38-978_com termux](https://user-images.githubusercontent.com/84581911/167410213-c3cd84cc-e1f0-4679-be37-610ee705ddb6.jpg)
![Screenshot_2022-05-09-20-28-37-198_com termux](https://user-images.githubusercontent.com/84581911/167410217-07b0da5d-268f-4712-ac9e-48087e3bb3ce.jpg)
![Screenshot_2022-05-09-20-28-35-601_com termux](https://user-images.githubusercontent.com/84581911/167410219-4c7e9baa-e309-44ac-8d9f-390d29ffff0f.jpg)
![Screenshot_2022-05-09-20-28-33-791_com termux](https://user-images.githubusercontent.com/84581911/167410225-99f693e5-b2b9-4088-ba61-467e4bf1c49c.jpg)
![Screenshot_2022-05-09-20-28-31-015_com termux](https://user-images.githubusercontent.com/84581911/167410226-65dd93e6-9c72-45f7-a800-f4e91800ccb6.jpg)
![Screenshot_2022-05-09-20-28-29-078_com termux](https://user-images.githubusercontent.com/84581911/167410228-f26836e5-61dd-4889-913d-d8b47935541e.jpg)
![Screenshot_2022-05-09-20-28-16-063_com termux](https://user-images.githubusercontent.com/84581911/167410236-71b231ab-8ad1-40db-8813-6f02d25266ef.jpg)
![Screenshot_2022-05-09-20-28-23-214_com termux](https://user-images.githubusercontent.com/84581911/167410239-cae843a2-5df0-455c-8efb-5404548007a2.jpg)
![Screenshot_2022-05-09-20-28-26-639_com termux](https://user-images.githubusercontent.com/84581911/167410243-ecedbeae-657e-413a-88f6-46b2bf240852.jpg)
![Screenshot_2022-05-09-20-27-10-049_com termux](https://user-images.githubusercontent.com/84581911/167410248-d5889d01-1c81-4782-b52a-f4ff3c78cc02.jpg)
![Screenshot_2022-05-09-20-27-04-346_com termux](https://user-images.githubusercontent.com/84581911/167410249-583953a9-4083-4da1-9270-3e5db1036bb6.jpg)

**Comment by yutong-yt** [comment]
非常迷惑
![Screenshot_2022-05-09-20-56-05-080_com termux](https://user-images.githubusercontent.com/84581911/167415450-af87bbf9-2984-4d09-b65c-c72291d63a0a.jpg)
![Screenshot_2022-05-09-20-55-41-641_com termux](https://user-images.githubusercontent.com/84581911/167415459-27c98d96-add1-4ad6-a753-4b7a1fced8dd.jpg)
![Screenshot_2022-05-09-20-55-36-491_com termux](https://user-images.githubusercontent.com/84581911/167415464-b4a0231e-dfde-47c2-be67-56f3505aa92b.jpg)
，这是什么情况？

**Comment by Lzhiyong** [comment]
提交问题不要发送这么多截图，只需把最关键的错误提示粘贴上来，文本过大就上传 `txt` 文件，这样就可以了
这个错误来源于 `BLocationConfig.aidl`这个文件，你把包名改下就可以了(和其它两aidl文件包名一样)，后面还有几个kotlin源码的错误: `overrides nothing`，这个你应该可以自行搞定吧！

**Comment by Lzhiyong** [comment]
这个问题与aidl本身不相关，所以close掉
