### ISSUE TITLE
cmake error at build googletest

### ISSUE THREAD

**Issue by Mame29** [Lzhiyong/sdk-tools#22]
I have any error
![Screenshot_20221005_112801](https://user-images.githubusercontent.com/72637907/193981412-537fecca-15e1-4502-b92b-a46835a09bee.jpg)

How to fix it ?

**Comment by Lzhiyong** [comment]
[https://github.com/Lzhiyong/sdk-tools/blob/master/patches/cmake/protobuf_CMakeLists.txt.patch](https://github.com/Lzhiyong/sdk-tools/blob/master/patches/cmake/protobuf_CMakeLists.txt.patch)

**Comment by Lzhiyong** [comment]
Please download the `Platform Tools 33.0.3`, I have updated the build script
