### ISSUE TITLE
添加对高版本 Android-Gradle 的支持

### ISSUE THREAD

**Issue by RinOrz** [Lzhiyong/sdk-tools#6]
目前的版本无法编译 android gradle 4.1.0 以上的项目

**Comment by Lzhiyong** [comment]
> 目前的版本无法编译 android gradle 4.1.0 以上的项目

最新gradle:4.1.2可以正常编译，我现在用的就是这个版本，请参考[build-app](https://github.com/Lzhiyong/termux-ndk/tree/master/build-app)
