### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by masterjavaofficial** [Lzhiyong/sdk-tools#8]
Hello sir! Actually, I'm not reporting a issue, I need help!

I don't have a PC at the moment, but I want to keep developing on my phone. I've been trying to build one APK on ubuntu-20.04 (in proot-distro) using the openjdk-11-jdk, gradle and cmdline-tools (from the official Android Developer's website) since last month, but everytime failing when the task :app:mergeDebugResources runs. After some research I found that the aapt2 (also some other binaries) in build-tools which is downloaded by the sdkmanager is not compatible in my arm aarch64 phone. Thus, after searching a lot, I got to your repo. By the way, I don't know much how to use your repo to build the tools for my architecture (I will be helpful if you provide those for me).

Now I need the full instruction on how to successfully build an APK using Gradle, Java 8/11 and other necessary commandline tools in Termux. https://t.me/masterjavaofficial

**Comment by Lzhiyong** [comment]
[https://github.com/Lzhiyong/termux-ndk](https://github.com/Lzhiyong/termux-ndk)

[https://github.com/Lzhiyong/termux-ndk/tree/master/build-app](https://github.com/Lzhiyong/termux-ndk/tree/master/build-app)
